// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by lister-gen. DO NOT EDIT.

package v1

// GrafanaResourceDefinitionListerExpansion allows custom methods to be added to
// GrafanaResourceDefinitionLister.
type GrafanaResourceDefinitionListerExpansion interface{}
