//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	kinds "github.com/grafana/grafana-apiserver/pkg/apis/kinds"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceDefinition)(nil), (*kinds.GrafanaResourceDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceDefinition_To_kinds_GrafanaResourceDefinition(a.(*GrafanaResourceDefinition), b.(*kinds.GrafanaResourceDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceDefinition)(nil), (*GrafanaResourceDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceDefinition_To_v1_GrafanaResourceDefinition(a.(*kinds.GrafanaResourceDefinition), b.(*GrafanaResourceDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceDefinitionCondition)(nil), (*kinds.GrafanaResourceDefinitionCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceDefinitionCondition_To_kinds_GrafanaResourceDefinitionCondition(a.(*GrafanaResourceDefinitionCondition), b.(*kinds.GrafanaResourceDefinitionCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceDefinitionCondition)(nil), (*GrafanaResourceDefinitionCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceDefinitionCondition_To_v1_GrafanaResourceDefinitionCondition(a.(*kinds.GrafanaResourceDefinitionCondition), b.(*GrafanaResourceDefinitionCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceDefinitionList)(nil), (*kinds.GrafanaResourceDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceDefinitionList_To_kinds_GrafanaResourceDefinitionList(a.(*GrafanaResourceDefinitionList), b.(*kinds.GrafanaResourceDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceDefinitionList)(nil), (*GrafanaResourceDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceDefinitionList_To_v1_GrafanaResourceDefinitionList(a.(*kinds.GrafanaResourceDefinitionList), b.(*GrafanaResourceDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceDefinitionNames)(nil), (*kinds.GrafanaResourceDefinitionNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceDefinitionNames_To_kinds_GrafanaResourceDefinitionNames(a.(*GrafanaResourceDefinitionNames), b.(*kinds.GrafanaResourceDefinitionNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceDefinitionNames)(nil), (*GrafanaResourceDefinitionNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceDefinitionNames_To_v1_GrafanaResourceDefinitionNames(a.(*kinds.GrafanaResourceDefinitionNames), b.(*GrafanaResourceDefinitionNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceDefinitionSpec)(nil), (*kinds.GrafanaResourceDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceDefinitionSpec_To_kinds_GrafanaResourceDefinitionSpec(a.(*GrafanaResourceDefinitionSpec), b.(*kinds.GrafanaResourceDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceDefinitionStatus)(nil), (*kinds.GrafanaResourceDefinitionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceDefinitionStatus_To_kinds_GrafanaResourceDefinitionStatus(a.(*GrafanaResourceDefinitionStatus), b.(*kinds.GrafanaResourceDefinitionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceDefinitionStatus)(nil), (*GrafanaResourceDefinitionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceDefinitionStatus_To_v1_GrafanaResourceDefinitionStatus(a.(*kinds.GrafanaResourceDefinitionStatus), b.(*GrafanaResourceDefinitionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceDefinitionVersion)(nil), (*kinds.GrafanaResourceDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceDefinitionVersion_To_kinds_GrafanaResourceDefinitionVersion(a.(*GrafanaResourceDefinitionVersion), b.(*kinds.GrafanaResourceDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceDefinitionVersion)(nil), (*GrafanaResourceDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceDefinitionVersion_To_v1_GrafanaResourceDefinitionVersion(a.(*kinds.GrafanaResourceDefinitionVersion), b.(*GrafanaResourceDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceSubresourceHistory)(nil), (*kinds.GrafanaResourceSubresourceHistory)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceSubresourceHistory_To_kinds_GrafanaResourceSubresourceHistory(a.(*GrafanaResourceSubresourceHistory), b.(*kinds.GrafanaResourceSubresourceHistory), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceSubresourceHistory)(nil), (*GrafanaResourceSubresourceHistory)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceSubresourceHistory_To_v1_GrafanaResourceSubresourceHistory(a.(*kinds.GrafanaResourceSubresourceHistory), b.(*GrafanaResourceSubresourceHistory), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceSubresourceRef)(nil), (*kinds.GrafanaResourceSubresourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceSubresourceRef_To_kinds_GrafanaResourceSubresourceRef(a.(*GrafanaResourceSubresourceRef), b.(*kinds.GrafanaResourceSubresourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceSubresourceRef)(nil), (*GrafanaResourceSubresourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceSubresourceRef_To_v1_GrafanaResourceSubresourceRef(a.(*kinds.GrafanaResourceSubresourceRef), b.(*GrafanaResourceSubresourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceSubresourceScale)(nil), (*kinds.GrafanaResourceSubresourceScale)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceSubresourceScale_To_kinds_GrafanaResourceSubresourceScale(a.(*GrafanaResourceSubresourceScale), b.(*kinds.GrafanaResourceSubresourceScale), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceSubresourceScale)(nil), (*GrafanaResourceSubresourceScale)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceSubresourceScale_To_v1_GrafanaResourceSubresourceScale(a.(*kinds.GrafanaResourceSubresourceScale), b.(*GrafanaResourceSubresourceScale), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceSubresourceStatus)(nil), (*kinds.GrafanaResourceSubresourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceSubresourceStatus_To_kinds_GrafanaResourceSubresourceStatus(a.(*GrafanaResourceSubresourceStatus), b.(*kinds.GrafanaResourceSubresourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceSubresourceStatus)(nil), (*GrafanaResourceSubresourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceSubresourceStatus_To_v1_GrafanaResourceSubresourceStatus(a.(*kinds.GrafanaResourceSubresourceStatus), b.(*GrafanaResourceSubresourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrafanaResourceSubresources)(nil), (*kinds.GrafanaResourceSubresources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GrafanaResourceSubresources_To_kinds_GrafanaResourceSubresources(a.(*GrafanaResourceSubresources), b.(*kinds.GrafanaResourceSubresources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kinds.GrafanaResourceSubresources)(nil), (*GrafanaResourceSubresources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceSubresources_To_v1_GrafanaResourceSubresources(a.(*kinds.GrafanaResourceSubresources), b.(*GrafanaResourceSubresources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*kinds.GrafanaResourceDefinitionSpec)(nil), (*GrafanaResourceDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kinds_GrafanaResourceDefinitionSpec_To_v1_GrafanaResourceDefinitionSpec(a.(*kinds.GrafanaResourceDefinitionSpec), b.(*GrafanaResourceDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_GrafanaResourceDefinition_To_kinds_GrafanaResourceDefinition(in *GrafanaResourceDefinition, out *kinds.GrafanaResourceDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_GrafanaResourceDefinitionSpec_To_kinds_GrafanaResourceDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_GrafanaResourceDefinitionStatus_To_kinds_GrafanaResourceDefinitionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_GrafanaResourceDefinition_To_kinds_GrafanaResourceDefinition is an autogenerated conversion function.
func Convert_v1_GrafanaResourceDefinition_To_kinds_GrafanaResourceDefinition(in *GrafanaResourceDefinition, out *kinds.GrafanaResourceDefinition, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceDefinition_To_kinds_GrafanaResourceDefinition(in, out, s)
}

func autoConvert_kinds_GrafanaResourceDefinition_To_v1_GrafanaResourceDefinition(in *kinds.GrafanaResourceDefinition, out *GrafanaResourceDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kinds_GrafanaResourceDefinitionSpec_To_v1_GrafanaResourceDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kinds_GrafanaResourceDefinitionStatus_To_v1_GrafanaResourceDefinitionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kinds_GrafanaResourceDefinition_To_v1_GrafanaResourceDefinition is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceDefinition_To_v1_GrafanaResourceDefinition(in *kinds.GrafanaResourceDefinition, out *GrafanaResourceDefinition, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceDefinition_To_v1_GrafanaResourceDefinition(in, out, s)
}

func autoConvert_v1_GrafanaResourceDefinitionCondition_To_kinds_GrafanaResourceDefinitionCondition(in *GrafanaResourceDefinitionCondition, out *kinds.GrafanaResourceDefinitionCondition, s conversion.Scope) error {
	out.Type = kinds.GrafanaResourceDefinitionConditionType(in.Type)
	out.Status = kinds.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1_GrafanaResourceDefinitionCondition_To_kinds_GrafanaResourceDefinitionCondition is an autogenerated conversion function.
func Convert_v1_GrafanaResourceDefinitionCondition_To_kinds_GrafanaResourceDefinitionCondition(in *GrafanaResourceDefinitionCondition, out *kinds.GrafanaResourceDefinitionCondition, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceDefinitionCondition_To_kinds_GrafanaResourceDefinitionCondition(in, out, s)
}

func autoConvert_kinds_GrafanaResourceDefinitionCondition_To_v1_GrafanaResourceDefinitionCondition(in *kinds.GrafanaResourceDefinitionCondition, out *GrafanaResourceDefinitionCondition, s conversion.Scope) error {
	out.Type = GrafanaResourceDefinitionConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_kinds_GrafanaResourceDefinitionCondition_To_v1_GrafanaResourceDefinitionCondition is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceDefinitionCondition_To_v1_GrafanaResourceDefinitionCondition(in *kinds.GrafanaResourceDefinitionCondition, out *GrafanaResourceDefinitionCondition, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceDefinitionCondition_To_v1_GrafanaResourceDefinitionCondition(in, out, s)
}

func autoConvert_v1_GrafanaResourceDefinitionList_To_kinds_GrafanaResourceDefinitionList(in *GrafanaResourceDefinitionList, out *kinds.GrafanaResourceDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]kinds.GrafanaResourceDefinition, len(*in))
		for i := range *in {
			if err := Convert_v1_GrafanaResourceDefinition_To_kinds_GrafanaResourceDefinition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1_GrafanaResourceDefinitionList_To_kinds_GrafanaResourceDefinitionList is an autogenerated conversion function.
func Convert_v1_GrafanaResourceDefinitionList_To_kinds_GrafanaResourceDefinitionList(in *GrafanaResourceDefinitionList, out *kinds.GrafanaResourceDefinitionList, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceDefinitionList_To_kinds_GrafanaResourceDefinitionList(in, out, s)
}

func autoConvert_kinds_GrafanaResourceDefinitionList_To_v1_GrafanaResourceDefinitionList(in *kinds.GrafanaResourceDefinitionList, out *GrafanaResourceDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GrafanaResourceDefinition, len(*in))
		for i := range *in {
			if err := Convert_kinds_GrafanaResourceDefinition_To_v1_GrafanaResourceDefinition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_kinds_GrafanaResourceDefinitionList_To_v1_GrafanaResourceDefinitionList is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceDefinitionList_To_v1_GrafanaResourceDefinitionList(in *kinds.GrafanaResourceDefinitionList, out *GrafanaResourceDefinitionList, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceDefinitionList_To_v1_GrafanaResourceDefinitionList(in, out, s)
}

func autoConvert_v1_GrafanaResourceDefinitionNames_To_kinds_GrafanaResourceDefinitionNames(in *GrafanaResourceDefinitionNames, out *kinds.GrafanaResourceDefinitionNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.ShortNames = *(*[]string)(unsafe.Pointer(&in.ShortNames))
	out.Kind = in.Kind
	out.ListKind = in.ListKind
	out.Categories = *(*[]string)(unsafe.Pointer(&in.Categories))
	return nil
}

// Convert_v1_GrafanaResourceDefinitionNames_To_kinds_GrafanaResourceDefinitionNames is an autogenerated conversion function.
func Convert_v1_GrafanaResourceDefinitionNames_To_kinds_GrafanaResourceDefinitionNames(in *GrafanaResourceDefinitionNames, out *kinds.GrafanaResourceDefinitionNames, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceDefinitionNames_To_kinds_GrafanaResourceDefinitionNames(in, out, s)
}

func autoConvert_kinds_GrafanaResourceDefinitionNames_To_v1_GrafanaResourceDefinitionNames(in *kinds.GrafanaResourceDefinitionNames, out *GrafanaResourceDefinitionNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.ShortNames = *(*[]string)(unsafe.Pointer(&in.ShortNames))
	out.Kind = in.Kind
	out.ListKind = in.ListKind
	out.Categories = *(*[]string)(unsafe.Pointer(&in.Categories))
	return nil
}

// Convert_kinds_GrafanaResourceDefinitionNames_To_v1_GrafanaResourceDefinitionNames is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceDefinitionNames_To_v1_GrafanaResourceDefinitionNames(in *kinds.GrafanaResourceDefinitionNames, out *GrafanaResourceDefinitionNames, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceDefinitionNames_To_v1_GrafanaResourceDefinitionNames(in, out, s)
}

func autoConvert_v1_GrafanaResourceDefinitionSpec_To_kinds_GrafanaResourceDefinitionSpec(in *GrafanaResourceDefinitionSpec, out *kinds.GrafanaResourceDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_v1_GrafanaResourceDefinitionNames_To_kinds_GrafanaResourceDefinitionNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Scope = kinds.ResourceScope(in.Scope)
	out.Versions = *(*[]kinds.GrafanaResourceDefinitionVersion)(unsafe.Pointer(&in.Versions))
	if err := metav1.Convert_bool_To_Pointer_bool(&in.PreserveUnknownFields, &out.PreserveUnknownFields, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_GrafanaResourceDefinitionSpec_To_kinds_GrafanaResourceDefinitionSpec is an autogenerated conversion function.
func Convert_v1_GrafanaResourceDefinitionSpec_To_kinds_GrafanaResourceDefinitionSpec(in *GrafanaResourceDefinitionSpec, out *kinds.GrafanaResourceDefinitionSpec, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceDefinitionSpec_To_kinds_GrafanaResourceDefinitionSpec(in, out, s)
}

func autoConvert_kinds_GrafanaResourceDefinitionSpec_To_v1_GrafanaResourceDefinitionSpec(in *kinds.GrafanaResourceDefinitionSpec, out *GrafanaResourceDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	// WARNING: in.Version requires manual conversion: does not exist in peer-type
	if err := Convert_kinds_GrafanaResourceDefinitionNames_To_v1_GrafanaResourceDefinitionNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Scope = ResourceScope(in.Scope)
	// WARNING: in.Subresources requires manual conversion: does not exist in peer-type
	out.Versions = *(*[]GrafanaResourceDefinitionVersion)(unsafe.Pointer(&in.Versions))
	if err := metav1.Convert_Pointer_bool_To_bool(&in.PreserveUnknownFields, &out.PreserveUnknownFields, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_GrafanaResourceDefinitionStatus_To_kinds_GrafanaResourceDefinitionStatus(in *GrafanaResourceDefinitionStatus, out *kinds.GrafanaResourceDefinitionStatus, s conversion.Scope) error {
	out.Conditions = *(*[]kinds.GrafanaResourceDefinitionCondition)(unsafe.Pointer(&in.Conditions))
	if err := Convert_v1_GrafanaResourceDefinitionNames_To_kinds_GrafanaResourceDefinitionNames(&in.AcceptedNames, &out.AcceptedNames, s); err != nil {
		return err
	}
	out.StoredVersions = *(*[]string)(unsafe.Pointer(&in.StoredVersions))
	return nil
}

// Convert_v1_GrafanaResourceDefinitionStatus_To_kinds_GrafanaResourceDefinitionStatus is an autogenerated conversion function.
func Convert_v1_GrafanaResourceDefinitionStatus_To_kinds_GrafanaResourceDefinitionStatus(in *GrafanaResourceDefinitionStatus, out *kinds.GrafanaResourceDefinitionStatus, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceDefinitionStatus_To_kinds_GrafanaResourceDefinitionStatus(in, out, s)
}

func autoConvert_kinds_GrafanaResourceDefinitionStatus_To_v1_GrafanaResourceDefinitionStatus(in *kinds.GrafanaResourceDefinitionStatus, out *GrafanaResourceDefinitionStatus, s conversion.Scope) error {
	out.Conditions = *(*[]GrafanaResourceDefinitionCondition)(unsafe.Pointer(&in.Conditions))
	if err := Convert_kinds_GrafanaResourceDefinitionNames_To_v1_GrafanaResourceDefinitionNames(&in.AcceptedNames, &out.AcceptedNames, s); err != nil {
		return err
	}
	out.StoredVersions = *(*[]string)(unsafe.Pointer(&in.StoredVersions))
	return nil
}

// Convert_kinds_GrafanaResourceDefinitionStatus_To_v1_GrafanaResourceDefinitionStatus is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceDefinitionStatus_To_v1_GrafanaResourceDefinitionStatus(in *kinds.GrafanaResourceDefinitionStatus, out *GrafanaResourceDefinitionStatus, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceDefinitionStatus_To_v1_GrafanaResourceDefinitionStatus(in, out, s)
}

func autoConvert_v1_GrafanaResourceDefinitionVersion_To_kinds_GrafanaResourceDefinitionVersion(in *GrafanaResourceDefinitionVersion, out *kinds.GrafanaResourceDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	out.Served = in.Served
	out.Storage = in.Storage
	out.Deprecated = in.Deprecated
	out.DeprecationWarning = (*string)(unsafe.Pointer(in.DeprecationWarning))
	out.Subresources = (*kinds.GrafanaResourceSubresources)(unsafe.Pointer(in.Subresources))
	return nil
}

// Convert_v1_GrafanaResourceDefinitionVersion_To_kinds_GrafanaResourceDefinitionVersion is an autogenerated conversion function.
func Convert_v1_GrafanaResourceDefinitionVersion_To_kinds_GrafanaResourceDefinitionVersion(in *GrafanaResourceDefinitionVersion, out *kinds.GrafanaResourceDefinitionVersion, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceDefinitionVersion_To_kinds_GrafanaResourceDefinitionVersion(in, out, s)
}

func autoConvert_kinds_GrafanaResourceDefinitionVersion_To_v1_GrafanaResourceDefinitionVersion(in *kinds.GrafanaResourceDefinitionVersion, out *GrafanaResourceDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	out.Served = in.Served
	out.Storage = in.Storage
	out.Deprecated = in.Deprecated
	out.DeprecationWarning = (*string)(unsafe.Pointer(in.DeprecationWarning))
	out.Subresources = (*GrafanaResourceSubresources)(unsafe.Pointer(in.Subresources))
	return nil
}

// Convert_kinds_GrafanaResourceDefinitionVersion_To_v1_GrafanaResourceDefinitionVersion is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceDefinitionVersion_To_v1_GrafanaResourceDefinitionVersion(in *kinds.GrafanaResourceDefinitionVersion, out *GrafanaResourceDefinitionVersion, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceDefinitionVersion_To_v1_GrafanaResourceDefinitionVersion(in, out, s)
}

func autoConvert_v1_GrafanaResourceSubresourceHistory_To_kinds_GrafanaResourceSubresourceHistory(in *GrafanaResourceSubresourceHistory, out *kinds.GrafanaResourceSubresourceHistory, s conversion.Scope) error {
	return nil
}

// Convert_v1_GrafanaResourceSubresourceHistory_To_kinds_GrafanaResourceSubresourceHistory is an autogenerated conversion function.
func Convert_v1_GrafanaResourceSubresourceHistory_To_kinds_GrafanaResourceSubresourceHistory(in *GrafanaResourceSubresourceHistory, out *kinds.GrafanaResourceSubresourceHistory, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceSubresourceHistory_To_kinds_GrafanaResourceSubresourceHistory(in, out, s)
}

func autoConvert_kinds_GrafanaResourceSubresourceHistory_To_v1_GrafanaResourceSubresourceHistory(in *kinds.GrafanaResourceSubresourceHistory, out *GrafanaResourceSubresourceHistory, s conversion.Scope) error {
	return nil
}

// Convert_kinds_GrafanaResourceSubresourceHistory_To_v1_GrafanaResourceSubresourceHistory is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceSubresourceHistory_To_v1_GrafanaResourceSubresourceHistory(in *kinds.GrafanaResourceSubresourceHistory, out *GrafanaResourceSubresourceHistory, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceSubresourceHistory_To_v1_GrafanaResourceSubresourceHistory(in, out, s)
}

func autoConvert_v1_GrafanaResourceSubresourceRef_To_kinds_GrafanaResourceSubresourceRef(in *GrafanaResourceSubresourceRef, out *kinds.GrafanaResourceSubresourceRef, s conversion.Scope) error {
	return nil
}

// Convert_v1_GrafanaResourceSubresourceRef_To_kinds_GrafanaResourceSubresourceRef is an autogenerated conversion function.
func Convert_v1_GrafanaResourceSubresourceRef_To_kinds_GrafanaResourceSubresourceRef(in *GrafanaResourceSubresourceRef, out *kinds.GrafanaResourceSubresourceRef, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceSubresourceRef_To_kinds_GrafanaResourceSubresourceRef(in, out, s)
}

func autoConvert_kinds_GrafanaResourceSubresourceRef_To_v1_GrafanaResourceSubresourceRef(in *kinds.GrafanaResourceSubresourceRef, out *GrafanaResourceSubresourceRef, s conversion.Scope) error {
	return nil
}

// Convert_kinds_GrafanaResourceSubresourceRef_To_v1_GrafanaResourceSubresourceRef is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceSubresourceRef_To_v1_GrafanaResourceSubresourceRef(in *kinds.GrafanaResourceSubresourceRef, out *GrafanaResourceSubresourceRef, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceSubresourceRef_To_v1_GrafanaResourceSubresourceRef(in, out, s)
}

func autoConvert_v1_GrafanaResourceSubresourceScale_To_kinds_GrafanaResourceSubresourceScale(in *GrafanaResourceSubresourceScale, out *kinds.GrafanaResourceSubresourceScale, s conversion.Scope) error {
	out.SpecReplicasPath = in.SpecReplicasPath
	out.StatusReplicasPath = in.StatusReplicasPath
	out.LabelSelectorPath = (*string)(unsafe.Pointer(in.LabelSelectorPath))
	return nil
}

// Convert_v1_GrafanaResourceSubresourceScale_To_kinds_GrafanaResourceSubresourceScale is an autogenerated conversion function.
func Convert_v1_GrafanaResourceSubresourceScale_To_kinds_GrafanaResourceSubresourceScale(in *GrafanaResourceSubresourceScale, out *kinds.GrafanaResourceSubresourceScale, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceSubresourceScale_To_kinds_GrafanaResourceSubresourceScale(in, out, s)
}

func autoConvert_kinds_GrafanaResourceSubresourceScale_To_v1_GrafanaResourceSubresourceScale(in *kinds.GrafanaResourceSubresourceScale, out *GrafanaResourceSubresourceScale, s conversion.Scope) error {
	out.SpecReplicasPath = in.SpecReplicasPath
	out.StatusReplicasPath = in.StatusReplicasPath
	out.LabelSelectorPath = (*string)(unsafe.Pointer(in.LabelSelectorPath))
	return nil
}

// Convert_kinds_GrafanaResourceSubresourceScale_To_v1_GrafanaResourceSubresourceScale is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceSubresourceScale_To_v1_GrafanaResourceSubresourceScale(in *kinds.GrafanaResourceSubresourceScale, out *GrafanaResourceSubresourceScale, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceSubresourceScale_To_v1_GrafanaResourceSubresourceScale(in, out, s)
}

func autoConvert_v1_GrafanaResourceSubresourceStatus_To_kinds_GrafanaResourceSubresourceStatus(in *GrafanaResourceSubresourceStatus, out *kinds.GrafanaResourceSubresourceStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_GrafanaResourceSubresourceStatus_To_kinds_GrafanaResourceSubresourceStatus is an autogenerated conversion function.
func Convert_v1_GrafanaResourceSubresourceStatus_To_kinds_GrafanaResourceSubresourceStatus(in *GrafanaResourceSubresourceStatus, out *kinds.GrafanaResourceSubresourceStatus, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceSubresourceStatus_To_kinds_GrafanaResourceSubresourceStatus(in, out, s)
}

func autoConvert_kinds_GrafanaResourceSubresourceStatus_To_v1_GrafanaResourceSubresourceStatus(in *kinds.GrafanaResourceSubresourceStatus, out *GrafanaResourceSubresourceStatus, s conversion.Scope) error {
	return nil
}

// Convert_kinds_GrafanaResourceSubresourceStatus_To_v1_GrafanaResourceSubresourceStatus is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceSubresourceStatus_To_v1_GrafanaResourceSubresourceStatus(in *kinds.GrafanaResourceSubresourceStatus, out *GrafanaResourceSubresourceStatus, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceSubresourceStatus_To_v1_GrafanaResourceSubresourceStatus(in, out, s)
}

func autoConvert_v1_GrafanaResourceSubresources_To_kinds_GrafanaResourceSubresources(in *GrafanaResourceSubresources, out *kinds.GrafanaResourceSubresources, s conversion.Scope) error {
	out.Status = (*kinds.GrafanaResourceSubresourceStatus)(unsafe.Pointer(in.Status))
	out.Scale = (*kinds.GrafanaResourceSubresourceScale)(unsafe.Pointer(in.Scale))
	out.History = (*kinds.GrafanaResourceSubresourceHistory)(unsafe.Pointer(in.History))
	out.Ref = (*kinds.GrafanaResourceSubresourceRef)(unsafe.Pointer(in.Ref))
	return nil
}

// Convert_v1_GrafanaResourceSubresources_To_kinds_GrafanaResourceSubresources is an autogenerated conversion function.
func Convert_v1_GrafanaResourceSubresources_To_kinds_GrafanaResourceSubresources(in *GrafanaResourceSubresources, out *kinds.GrafanaResourceSubresources, s conversion.Scope) error {
	return autoConvert_v1_GrafanaResourceSubresources_To_kinds_GrafanaResourceSubresources(in, out, s)
}

func autoConvert_kinds_GrafanaResourceSubresources_To_v1_GrafanaResourceSubresources(in *kinds.GrafanaResourceSubresources, out *GrafanaResourceSubresources, s conversion.Scope) error {
	out.Status = (*GrafanaResourceSubresourceStatus)(unsafe.Pointer(in.Status))
	out.Scale = (*GrafanaResourceSubresourceScale)(unsafe.Pointer(in.Scale))
	out.History = (*GrafanaResourceSubresourceHistory)(unsafe.Pointer(in.History))
	out.Ref = (*GrafanaResourceSubresourceRef)(unsafe.Pointer(in.Ref))
	return nil
}

// Convert_kinds_GrafanaResourceSubresources_To_v1_GrafanaResourceSubresources is an autogenerated conversion function.
func Convert_kinds_GrafanaResourceSubresources_To_v1_GrafanaResourceSubresources(in *kinds.GrafanaResourceSubresources, out *GrafanaResourceSubresources, s conversion.Scope) error {
	return autoConvert_kinds_GrafanaResourceSubresources_To_v1_GrafanaResourceSubresources(in, out, s)
}
