//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&GrafanaResourceDefinition{}, func(obj interface{}) { SetObjectDefaults_GrafanaResourceDefinition(obj.(*GrafanaResourceDefinition)) })
	scheme.AddTypeDefaultingFunc(&GrafanaResourceDefinitionList{}, func(obj interface{}) {
		SetObjectDefaults_GrafanaResourceDefinitionList(obj.(*GrafanaResourceDefinitionList))
	})
	return nil
}

func SetObjectDefaults_GrafanaResourceDefinition(in *GrafanaResourceDefinition) {
	SetDefaults_GrafanaResourceDefinition(in)
	SetDefaults_GrafanaResourceDefinitionSpec(&in.Spec)
}

func SetObjectDefaults_GrafanaResourceDefinitionList(in *GrafanaResourceDefinitionList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_GrafanaResourceDefinition(a)
	}
}
