apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.kinds.grafana.com
spec:
  insecureSkipTLSVerify: true
  group: kinds.grafana.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: ext-api
    namespace: grafana
    port: 8443
  version: v1
