---
apiVersion: v1
kind: Endpoints
metadata:
  name: ext-api
subsets:
  - addresses:
      - ip: 172.17.0.1 # this is the gateway IP in the "bridge" docker network
    ports:
      - appProtocol: https
        port: 8443
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ext-api
spec:
  ports:
    - protocol: TCP
      appProtocol: https
      port: 8443
      targetPort: 8443
